# Generated by Django 5.1.2 on 2024-11-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('address_st_num', models.IntegerField()),
                ('address_name', models.IntegerField()),
                ('address_apt_num', models.IntegerField()),
                ('address_zip', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('dor', models.DateTimeField()),
                ('party', models.TextField()),
                ('precinct_num', models.IntegerField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v20primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
