# Generated by Django 5.1.2 on 2024-11-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='address_apt_num',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dor',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_num',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20primary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.TextField(),
        ),
    ]
