# Generated by Django 5.1.3 on 2024-11-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_profile_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='kill_ratio',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
