# Generated by Django 5.1.3 on 2024-12-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_feedbackresponse_rating_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='rating',
        ),
    ]
