# Generated by Django 5.1.2 on 2024-10-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_remove_statusmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
